title: "Luis Huesca"
description: "Senior Unity Developer Portfolio"
url: "https://luishuesca.github.io"
baseurl: ""   # MUY importante: vacío para repos tipo usuario.github.io

remote_theme: jeromelachaud/freelancer-theme

plugins:
  - jekyll-remote-theme

# Datos del contacto del tema
email: "tu-correo@dominio.com"

# Opcional, pero útil:
markdown: kramdown
permalink: pretty
