title: "Luis Huesca"
description: "Senior Unity Developer Portfolio"

url: "https://danohuescaunity.github.io"  # ojo: tu nuevo dominio de Pages
baseurl: ""                               # vac√≠o porque es repo tipo usuario.github.io

remote_theme: jeromelachaud/freelancer-theme

plugins:
  - jekyll-remote-theme

markdown: kramdown
permalink: pretty

email: "tu-correo@dominio.com"
